## **Частина 1**. Робота з **масивами, векторами та текстами**

**Завдання 1**

In [ ]:
import numpy as np

vector = np.arange(1, 11)

print("Vector:", vector)

Vector: [ 1  2  3  4  5  6  7  8  9 10]


**Завдання 2**

In [ ]:
import numpy as np

matrix = np.zeros((3, 3), dtype=int)

print(matrix)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


**Завдання 3**

In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(5, 5))

print(matrix)


[[ 9  5  1  3  1]
 [ 5  6  7  5  8]
 [ 5  2  3  2  5]
 [10  7  5  8  2]
 [ 5 10  9  8  2]]


**Завдання 4**

In [ ]:
import numpy as np

matrix = np.random.rand(4, 4)

print(matrix)


[[0.33697951 0.01651608 0.66543643 0.1217533 ]
 [0.89677706 0.6235966  0.52191562 0.15416705]
 [0.05040277 0.17567496 0.86569656 0.46001389]
 [0.47190359 0.3396193  0.00854953 0.99232967]]


**Завдання 5**

In [ ]:
import numpy as np

arr1 = np.random.randint(1, 11, size=5)
arr2 = np.random.randint(1, 11, size=5)

print("(+):    ", arr1 + arr2)
print("(-):   ", arr1 - arr2)
print("(*):     ", arr1 * arr2)

(+):     [ 7 14 13  7 18]
(-):    [ 5  0  7 -3  0]
(*):      [ 6 49 30 10 81]


**Завдання 6**

In [ ]:
import numpy as np

vector1 = np.random.randint(1, 6, size=7)
vector2 = np.random.randint(1, 6, size=7)

dot_product = np.dot(vector1, vector2)

print(dot_product)

63


**Завдання 7**

In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))

matrix2 = np.random.randint(1, 11, size=(2, 3))

mult = np.dot(matrix1, matrix2)
print(mult)

[[ 57  30  30]
 [136  64  82]]


**Завдання 8**

In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

det = np.linalg.det(matrix)

if det == 0:
  print("Оберненої матриці не існує")
else:
  inverse_matrix = np.linalg.inv(matrix)
  print(inverse_matrix)

[[ 0.65116279 -0.58139535  0.04651163]
 [-0.27906977  0.53488372 -0.1627907 ]
 [-0.06976744 -0.11627907  0.20930233]]


**Завдання 9**

In [ ]:
import numpy as np

martix = np.random.rand(4, 4)

transposed_matrix = matrix.T

print(transposed_matrix)

[[4 3 3]
 [5 6 5]
 [3 4 8]]


**Завдання 10**

In [5]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print(np.dot(matrix, vector))

[176 155  87]


**Завдання 11**

In [8]:
import numpy as np

matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print(np.dot(matrix, vector))

[0.73195871 0.95799537]


**Завдання 12**

In [ ]:
import numpy as np

m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))

print(m1 * m2)

**Завдання 13**

In [9]:
import numpy as np

m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))

print(np.dot(m1, m2))

[[40 73]
 [37 98]]


**Завдання 14**

In [10]:
import numpy as np

m = np.random.randint(1, 101, size=(5, 5))
print(np.sum(m))

1222


**Завдання 15**

In [11]:
import numpy as np

m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))

print(m1 - m2)

[[-7  1  3  6]
 [ 5 -2 -1 -1]
 [ 0  0  3 -4]
 [-6 -5 -2  1]]


**Завдання 16**

In [12]:
import numpy as np

m = np.random.rand(3, 3)
sum = np.sum(m, axis=1, keepdims=True)
print(sum)

[[2.31530539]
 [0.75509788]
 [1.64225775]]


**Завдання 17**

In [13]:
import numpy as np

matrix = np.random.randint(1, 11, size=(13, 13))
squared_matrix = matrix ** 2
print(squared_matrix)

[[ 64  25  16  36   4 100 100  64   1  49  16  36  81]
 [ 16 100  16  16  16  49   1  49   4  49  25   9  49]
 [ 81   4  16   9  36  49  16  81   9   4   9   1   4]
 [100  64   9   4  16  36  16   9   9   4  81  49   1]
 [ 64   4   4  16  64   4  16  64 100  81   9  16  81]
 [ 64  16  81   1  49   4  64  36  81 100   9   1  16]
 [ 16   1   9   4   1  64   4   1  16   4  81   4  16]
 [  9   4 100  49  16   1 100  49   4 100   1   9   1]
 [  1  36   4 100 100   4  81   1  36   4   9  16   9]
 [ 64  64 100  25   9  64   1 100  81  36  16  16  16]
 [  4  64  25   9   4   1   4  81  64  36   1   4  25]
 [  9  49   9  36   1  36  81 100   4  81  36  64  25]
 [ 25   1   1  49  25   1  64  16   9  49  25  64  49]]


**Завдання 18**

In [14]:
import numpy as np

vector = np.random.randint(1, 51, size=4)
s_v = vector ** 2
print(s_v)

[  36  169 1369  256]
